languageCode = 'en-us'
title = "Aured's Site"
sectionPagesMenu = 'main'

[params]
  contentTypeName = "posts"
  fullWidthTheme = true

[params.logo]
  logoText = "Aured's Site"

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts/'
    weight = 20
  [[menus.main]]
    name = 'Friends'
    pageRef = '/friends/'
    weight = 30
  [[menus.main]]
    name = 'Miscellanea'
    pageRef = '/miscellanea/'
    weight = 40